### ISSUE TITLE
去哪里下载apk呢

### ISSUE THREAD

**Issue by heiyutian** [E7KMbb/AD-hosts#1]
我通过magisk刷入了AD-hosts，现在我应该装个APK吧，比如我刷了riru-edxposed，就要装个edxposed的APK来管理，请问AD-hosts的APK在哪里下载。

**Comment by heiyutian** [comment]
看了下hosts文件，原来都包括在这个文件里面了呀

**Comment by E7KMbb** [comment]
不需要app
