### ISSUE TITLE
使用后造成支付宝内饿了么等小程序几近瘫痪

### ISSUE THREAD

**Issue by zeno-d** [E7KMbb/AD-hosts#13]
安装模块后，最近版本的支付宝内很多小程序加载异常，几乎无法使用。卸载模块后，恢复正常。
能否给支付宝建个白名单？

**Comment by Thiasap** [comment]
这个东西没法做成白名单，全局的，只能抓包慢慢分析了

**Comment by E7KMbb** [comment]
使用AnyHosts自行编辑黑名单 https://github.com/E7KMbb/AnyHosts
