### ISSUE TITLE
好像失效了

### ISSUE THREAD

**Issue by LittleControl** [E7KMbb/AD-hosts#2]
安卓10+MIUI11
面具20.1
好像现在去除不了APP的启动广告的
以前应该是可以的，现在好像不可以了
还请依然的爱大佬适配一下吧😚

**Comment by boyliuxiaopeng** [comment]
MIUI 10 9.9.3开发版+面具V20.2，瑟瑟发抖

**Comment by E7KMbb** [comment]
是否安有其他的hosts模块？

**Comment by LittleControl** [comment]
> 是否安有其他的hosts模块？

没有装有其他hosts模块，经测试，只是应用的启动页广告还有，但是浏览器的广告还是可以过滤掉的
然后感觉是一些应用的启动页广告换源了吧QAQ

**Comment by LittleControl** [comment]
除了启动页广告以外，别的功能还是很正常的，应该就是应用的启动广告换源了

**Comment by boyliuxiaopeng** [comment]
没有管，直接安装了现有版本，等待作者更新吧

李小控 <notifications@github.com> 于2019年11月16日周六 下午4:56写道：

**Comment by star2k** [comment]
坐等更新，作者加油！
