### ISSUE TITLE
host to block didi AD/update

### ISSUE THREAD

**Issue by WanderMax** [E7KMbb/AD-hosts#3]
127.0.0.1       apm.xiaojukeji.com
127.0.0.1       conf.diditaxi.com.cn
127.0.0.1       file.xmpush.xiaomi.com
127.0.0.1       thanos.xiaojukeji.com
127.0.0.1       resolver.msg.xiaomi.net
127.0.0.1       adtrack.xiaojukeji.com
127.0.0.1       ct.xiaojukeji.com
127.0.0.1       img-ys011.didistatic.com
127.0.0.1       eos-marketing.es.xiaojukeji.com

**Comment by E7KMbb** [comment]
Thanks i will join:smile:
