### ISSUE TITLE
The home page of the 360 browser  is blocked

### ISSUE THREAD

**Issue by zhangweildlh** [E7KMbb/AD-hosts#4]
The home page(News and information) of the 360 browser (speed version) is blocked and new messages cannot be received。

**Comment by E7KMbb** [comment]
now fix

**Comment by zhangweildlh** [comment]
Thank you




------------------ 原始邮件 ------------------
发件人: &nbsp;"E7KMbb"<notifications@github.com&gt;;
发送时间: &nbsp;2020年3月31日(星期二)下午5:19
收件人: &nbsp;"E7KMbb/AD-hosts"<AD-hosts@noreply.github.com&gt;;
抄送: &nbsp;"张伟"<157947621@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: &nbsp;Re: [E7KMbb/AD-hosts] The home page of the 360 browser is blocked (#4)





 
now fix
