### ISSUE TITLE
网页知乎、CSDN、简书劫持广告屏蔽

### ISSUE THREAD

**Issue by Henvy-Mango** [E7KMbb/AD-hosts#6]
127.0.0.1 api.bd.gl.com
127.0.0.1 cdn-7n.pt.zbwowo.com
127.0.0.1 statc.91feiyong.com
127.0.0.1 js.shshoushu.com
127.0.0.1 ad-channel.wikawika.xyz
127.0.0.1 ad-display.wikawika.xyz

**Comment by E7KMbb** [comment]
感谢您的提供
